version: '3.4'

services:
  # database:
  #   container_name: database
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: symfony
  #     MYSQL_USER: symfony
  #     MYSQL_PASSWORD: symfony
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - symfony
  postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
            - POSTGRES_DB=app
        ports:
            - '54004:5432'
        networks:
            - symfony
  php:
    container_name: php
    build:
      context: ./docker/php
    restart: always
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - ./code:/var/www/html
    networks:
      - symfony
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./code:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
  
     
networks:
    symfony:
        driver: bridge  



      
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
