name: Symfony

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       ref: develop
    - name: Setup PHP Action 
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - name: ls
      run: ls -la
    - name: Setup Symfony
      run: cp .env .env.local
    - name: Install Composer Dependencies
      run: composer install --prefer-dist
      
  my_second_job:
    runs-on: ubuntu-latest
    
    name: My second job

