name: Symfony

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP Action 
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - name: ls
      run: ls -l
   # - name: ls code
   #   working-directory: ./code
  #    run: ls -l 
    - uses: actions/checkout@v1
    - name: Setup Symfony
  #    working-directory: ./code
      run: cp .env .env.local
    - name: Install Composer Dependencies
    #  working-directory: ./code
      run: composer install --prefer-dist
 #   - name: Run Tests
 #     working-directory: ./code
  #    run: php bin/phpunit
